services:
  - type: web
    name: site-policia-mumias
    runtime: node
    plan: free
    branch: main
    buildCommand: bun install && bun run build
    startCommand: node .output/server/index.mjs
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
